### ISSUE TITLE
Repo issues

### ISSUE THREAD

**Issue by alexey-voronenko** [fordelive/watir_test#1]
1. `.idea` - ide specific files should be excluded from repository use .gitignore for that
2. Split test cases into separate files e.g. tc 03.1 03.2 03.3 can be in one file but tc_01 and tc_02 should be in separate files
3. Provide a simple README.md how to run your test suite

Make changes in separate branch and provide link to PR

**Comment by fordelive** [comment]
Hi there!
Done, please review.
